modbus_controller:
  - id: eastron
    modbus_id: modbus_eastron
    address: 0x1 # Meter address
    server_registers:
      - address: 0x0000 # Phase 1 line to neutral volts.
        value_type: FP32
        read_lambda: |-
          ESP_LOGI("energy_meter","Phase 1 line to neutral volts.");
          return 230.2;
          return id(a_voltage_sensor).state;
      - address: 0x0002 # Phase 2 line to neutral volts.
        value_type: FP32
        read_lambda: |-
          return id(b_voltage_sensor).state;
      - address: 0x0004 # Phase 3 line to neutral volts.
        value_type: FP32
        read_lambda: |-
          return id(c_voltage_sensor).state;
      - address: 0x0006 # Phase 1 current.
        value_type: FP32
        read_lambda: |-
          ESP_LOGI("energy_meter"," Phase 1 current.");
          return id(a_current_sensor).state;
      - address: 0x0008 # Phase 2 current.
        value_type: FP32
        read_lambda: |-
          return id(b_current_sensor).state;
      - address: 0x000A # Phase 3 current.
        value_type: FP32
        read_lambda: |-
          return id(b_current_sensor).state;
      - address: 0x000C # Phase 1 power.
        value_type: FP32
        read_lambda: |-
          return id(a_power_sensor).state;
      - address: 0x000E # Phase 2 power.
        value_type: FP32
        read_lambda: |-
          return id(b_power_sensor).state;
      - address: 0x0010 # Phase 3 power.
        value_type: FP32
        read_lambda: |-
          return id(c_power_sensor).state;     
      - address: 0x0012 # Phase 1 volt amps.
        value_type: FP32
        read_lambda: |-
          return id(a_power_sensor).state;
      - address: 0x0014 # Phase 2 volt amps.
        value_type: FP32
        read_lambda: |-
          return id(b_power_sensor).state;
      - address: 0x0016 # Phase 3 volt amps.
        value_type: FP32
        read_lambda: |-
          return id(c_power_sensor).state;
      - address: 0x0018 # Phase 1 volt amps reactive.
        value_type: FP32
        read_lambda: |-
          return 0.0;   
      - address: 0x001A # Phase 2 volt amps reactive.
        value_type: FP32
        read_lambda: |-
          return 0.0;   
      - address: 0x001C # Phase 3 volt amps reactive.
        value_type: FP32
        read_lambda: |-
          return 0.0;   
      - address: 0x001E # Phase 1 power factor.
        value_type: FP32
        read_lambda: |-
          return 1.0;   // pure resistive load
      - address: 0x0020 # Phase 2 power factor.
        value_type: FP32
        read_lambda: |-
          return 1.0;   // pure resistive load
      - address: 0x0022 # Phase 3 power factor.
        value_type: FP32
        read_lambda: |-
          return 1.0;   // pure resistive load
      - address: 0x0024 # Phase 1 phase angle.
        value_type: FP32
        read_lambda: |-
          return 0.0;   // ideal         
      - address: 0x0026 # Phase 2 phase angle.
        value_type: FP32
        read_lambda: |-
          return 0.0;   // ideal 
      - address: 0x0028 # Phase 3 phase angle.
        value_type: FP32
        read_lambda: |-
          return 0.0;   // ideal   
      - address: 0x002A # Average line to neutral volts.
        value_type: FP32
        read_lambda: |-
          return 230.0; 
      - address: 0x002C # Line-to-Neutral Voltage on Phase 2 (V2N) ???
        value_type: FP32
        read_lambda: |-
          return 230.0;                    
      - address: 0x002E # Average line current.
        value_type: FP32
        read_lambda: |-
          return (id(a_current_sensor).state+id(b_current_sensor).state+id(c_current_sensor).state)/3.0;                    
      - address: 0x0030 # Sum of line currents.
        value_type: FP32
        read_lambda: |-
          return id(a_current_sensor).state+id(b_current_sensor).state+id(c_current_sensor).state;   
      - address: 0x0032 # ????
        value_type: FP32
        read_lambda: |-
          return 0.0;      
      - address: 0x0034 # Total system power.
        value_type: FP32
        read_lambda: |-
          return id(total_act_power_sensor).state;
      - address: 0x0036 # Frequency of supply voltages.
        value_type: FP32
        read_lambda: |-
          return 50.0;                              
      - address: 0x0038 # Total system volt amps.
        value_type: FP32
        read_lambda: |-
          return id(total_act_power_sensor).state;
      - address: 0x003A # ????
        value_type: FP32
        read_lambda: |-
          return 0.0;
      - address: 0x003C # Total system VAr.
        value_type: FP32
        read_lambda: |-
          return 0.0;
      - address: 0x003E # Total system power factor.
        value_type: FP32
        read_lambda: |-
          return 1.0;
      - address: 0x0040 # ????
        value_type: FP32
        read_lambda: |-
          return 0.0;          
      - address: 0x0042 # Total system phase angle.
        value_type: FP32
        read_lambda: |-
          return 0.0;         
      - address: 0x0044 # ????
        value_type: FP32
        read_lambda: |-
          return 0.0;        
      - address: 0x0046 # Frequency of supply voltages.
        value_type: FP32
        read_lambda: |-
          return id(frequency_sensor).state;   
      - address: 0x0048 # Import Wh since last reset.
        value_type: FP32
        read_lambda: |-
          return 0.0;   
      - address: 0x0048 # Import Wh since last reset.
        value_type: FP32
        read_lambda: |-
          return 0.0;   
      - address: 0x004A # Export Wh since last reset.
        value_type: FP32
        read_lambda: |-
          return id(total_kwh_sensor).state;
      - address: 0x004C # Import VArh since last reset.
        value_type: FP32
        read_lambda: |-
          return 0.0;
      - address: 0x004E # Export VArh since last reset.
        value_type: FP32
        read_lambda: |-
          return 0.0;


sensor:
  - platform: template
    name: "Phase A Voltage"
    id: a_voltage_sensor
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_id: ${energy_meter_device_id}

  - platform: template
    name: "Phase B Voltage"
    id: b_voltage_sensor
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_id: ${energy_meter_device_id}
    
  - platform: template
    name: "Phase C Voltage"
    id: c_voltage_sensor
    unit_of_measurement: "V"
    accuracy_decimals: 2
    device_id: ${energy_meter_device_id}

  - platform: template
    name: "Phase A Current"
    id: a_current_sensor
    unit_of_measurement: "A"
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
      
  - platform: template
    name: "Phase B Current"
    id: b_current_sensor
    unit_of_measurement: "A"
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Phase C Current"
    id: c_current_sensor
    unit_of_measurement: "A"
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Phase A Active Power"
    id: a_power_sensor
    unit_of_measurement: "W"
    accuracy_decimals: 1
    device_id: ${energy_meter_device_id}
    
  - platform: template
    name: "Phase B Active Power"
    id: b_power_sensor
    unit_of_measurement: "W"
    accuracy_decimals: 1
    device_id: ${energy_meter_device_id}

  - platform: template
    name: "Phase C Active Power"
    id: c_power_sensor
    unit_of_measurement: "W"
    accuracy_decimals: 1
    device_id: ${energy_meter_device_id}

  - platform: template
    name: "Phase A Apparent Power"
    id: a_apparent_sensor
    unit_of_measurement: "VA"
    accuracy_decimals: 1
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Phase B Apparent Power"
    id: b_apparent_sensor
    unit_of_measurement: "VA"
    accuracy_decimals: 1
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Phase C Apparent Power"
    id: c_apparent_sensor
    unit_of_measurement: "VA"
    accuracy_decimals: 1
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Phase A Power Factor"
    id: a_pf_sensor
    unit_of_measurement: ""
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Phase B Power Factor"
    id: b_pf_sensor
    unit_of_measurement: ""
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Phase C Power Factor"
    id: c_pf_sensor
    unit_of_measurement: ""
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
  
  - platform: template
    name: "Average Line Current"
    id: average_current_sensor
    unit_of_measurement: "A"
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
    
  - platform: template
    name: "Total Line Current"
    id: total_current_sensor
    unit_of_measurement: "A"
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}
    
  - platform: template
    name: "Total Active Power"
    id: total_act_power_sensor
    unit_of_measurement: "W"
    accuracy_decimals: 1
    device_id: ${energy_meter_device_id}
    
  - platform: template
    name: "Total Apparent Power"
    id: total_aprt_power_sensor
    unit_of_measurement: "VA"
    accuracy_decimals: 1

  - platform: template
    name: "Supply Frequency"
    id: frequency_sensor
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    device_id: ${energy_meter_device_id}
    
  - platform: template
    name: "Total Energy kWh"
    id: total_kwh_sensor
    unit_of_measurement: "kWh"
    accuracy_decimals: 3
    device_id: ${energy_meter_device_id}