# https://esphome.io/components/modbus_controller/#example-server

esphome:
  name: example-modbus-server
  on_boot: 
    then:
      - lambda: |-
          id(evse_voltage_l1).publish_state(2304);

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dB
  power_save_mode: none  # Better reliability over power saving  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Modbus Server Hotspot"
    password: secret wifi_password

captive_portal:
  

uart:
# GPIO20 - RX to RXD of top RS485 module
# GPIO21 - TX to TXD of top RS485 module
  - id: uart_modbus_client
    tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 9600
    debug: 
      direction: BOTH

  # GPIO6 - RX to RXD of middle RS485 module
  # GPIO5 - TX to TXD of middle RS485 module
  - id: uart_modbus_server
    rx_pin: GPIO6
    tx_pin: GPIO5
    baud_rate: 9600
    debug:
      direction: BOTH
modbus:
  - uart_id: uart_modbus_client
    id: modbus_client
  - uart_id: uart_modbus_server
    id: modbus_server
    role: server

modbus_controller:
  - id: modbus_evse
    modbus_id: modbus_client
    address: 0x4
    update_interval: 5s
  - modbus_id: modbus_server
    address: 0x4
    server_registers:
      - address: 0x0002
        value_type: S_DWORD_R
        read_lambda: |-
          return 10*id(evse_voltage_l1).state;

sensor:
  - platform: modbus_controller
    id: evse_voltage_l1
    modbus_controller_id: modbus_evse
    name: "EVSE voltage L1"
    register_type: holding
    address: 0x0002
    device_class: voltage
    value_type: S_DWORD_R
    accuracy_decimals: 1
    unit_of_measurement: V
    filters:
      - multiply: 0.1


  # =========== Diagnostic sensors ===========
#sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    id: wifi_rssi
    update_interval: 1min  
    unit_of_measurement: "dBm"
    accuracy_decimals: 0
    device_class: signal_strength
    entity_category: diagnostic 

# Enable built-in status LED on GPIO8
light:
  - platform: status_led
    id: esp_status_led
    pin:
      number: GPIO8
      inverted: true
      ignore_strapping_warning: true
    entity_category: diagnostic      

# status_led:
#   pin: 
#     number: GPIO8
#     inverted: true
#     ignore_strapping_warning: true

