# Fake eastron 

esphome:
  name: fake-eastron-example
  friendly_name: Deye bridge for SDM630
  min_version: 2026.1.0 

esp32:
  board: esp32-c3-devkitc-02
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dB
  power_save_mode: none  # Better reliability over power saving  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Deye Fallback Hotspot"
    password: "blablabla"


uart:
  - id: uart_meter
    tx_pin: GPIO20
    rx_pin: GPIO21 
    baud_rate: 9600
    debug:
      direction: BOTH
modbus:
  - id: modbus_eastron
    uart_id: uart_meter
    role: server # https://esphome.io/components/modbus_controller/#example-server

# Include packages for Eastron
packages:
   energy_meter: !include
     file: fake-eastron.yaml
     vars:
       ct_update_interval: 5s


  # =========== Diagnostic sensors ===========
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    id: wifi_rssi
    update_interval: 1min  
    unit_of_measurement: "dBm"
    accuracy_decimals: 0
    device_class: signal_strength
    entity_category: diagnostic 

# Enable built-in status LED on GPIO8
light:
  - platform: status_led
    id: esp_status_led
    pin:
      number: GPIO8
      inverted: true
      ignore_strapping_warning: true
    entity_category: diagnostic      