substitutions:
  name: energy-meter                                                    #name in ESPhome
  device_description: "Deye Modbus-TCP bridge"   #Description in ESPhome
  modbus_controller_id: sg04lp3                                      #just a random name for the modbus controler
  device_type: sun12k                                                #all entities in Home Assistant will start with this text to help identify the entitys 

esphome:
  name: ${name}
  # on_boot: 
  #   then:
  #     - lambda: 
  #         id(mb_bridge).set_debug(true);    

esp32:
  board: esp32-s3-fh4r2 # ESP32-S3 zero board
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  networks:
    - ssid: !secret wifi_eteradxa_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_garaza_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  output_power: 8.5dB
  power_save_mode: none  # Better reliability over power saving  
  ap:
    ssid: ${name}

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/rosenrot00/esphome_modbus_bridge
    components: [modbus_bridge]


uart:
  # GPIO7 - TX to RX of bottom RS485 module
  # GPIO9 - RX to TX of bottom RS485 module
  - id: uart_bus
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 9600
    stop_bits: 1
    rx_buffer_size: 256  # minimum 256 recommended; increase for long RTU responses
    debug:
      direction: BOTH

modbus_bridge:
  id: mb_bridge
  uart_id: uart_bus
  rtu_response_timeout: 3000 
  tcp_client_timeout: 60000    # ms of inactivity before client is disconnected