esphome:
  name: modbus-logger
  friendly_name: modbus-logger
  devices: # https://esphome.io/components/esphome/#sub-devices
    - id: device_pace_bms1
      name: "PACE BMS Pack 1"
    - id: device_pace_bms2
      name: "PACE BMS Pack 2"
      

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  logs:
    sensor: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "TH7gnzlOBMC3ukK2ohQawQ5I7CSJ3pmVk3xmp5T8k3Q="

ota:
  - platform: esphome
    password: "18d5989648c58cc776f8d5492801db47"

wifi:
  networks:
    - ssid: !secret wifi_eteradxa_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_garaza_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  output_power: 8.5dB
  power_save_mode: none  # Better reliability over power saving  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Modbus Fallback Hotspot"
    password: "tLtXL20zmGbp"

captive_portal:


uart:
  # GPIO7 - TX to RX of bottom RS485 module
  # GPIO9 - RX to TX of bottom RS485 module
  - id: rs485
    tx_pin: GPIO6
    rx_pin: GPIO5
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: false

modbus:
  send_wait_time: 200ms
  uart_id: rs485
  id: mod_bus

modbus_controller:
  - id: pace_bms1
    address: 0x01
    modbus_id: mod_bus
    command_throttle: 200ms
    update_interval: 10s
  - id: pace_bms2
    address: 0x02
    modbus_id: mod_bus
    command_throttle: 200ms
    update_interval: 10s

# https://github.com/syssi/esphome-pace-bms/blob/main/multiple-batteries-example/pack.yaml
# binary_sensor:
#   - platform: modbus_controller
#     modbus_controller_id: pace_bms1
#     name: "Charging Operation"
#     address: 11
#     register_type: holding
#     bitmask: 0x0100

packages:
 bms1: !include
   file: pack.yaml
   vars:
     modbus_controller_id: pace_bms1
     device_id: device_pace_bms1
 bms2: !include
   file: pack.yaml
   vars:
     modbus_controller_id: pace_bms2
     device_id: device_pace_bms2


sensor:
# Diagnostic
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    id: wifi_rssi
    update_interval: 1min
    unit_of_measurement: "dBm"
    accuracy_decimals: 0
    device_class: signal_strength
    entity_category: diagnostic

# Enable built-in status LED on GPIO8
light:
  - platform: status_led
    id: esp_status_led
    pin:
      number: GPIO8
      inverted: true
      ignore_strapping_warning: true
    entity_category: diagnostic